# Generated by Django 4.2.5 on 2023-09-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_username', models.CharField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Type', models.CharField(max_length=100)),
                ('closed', models.BooleanField()),
                ('product_url', models.CharField(max_length=100)),
                ('actual_value', models.IntegerField()),
                ('product_buyer', models.CharField(max_length=100)),
                ('client_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='LeilaoApp.client')),
            ],
        ),
    ]
