# Generated by Django 4.2.5 on 2023-09-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='client_Id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_Type',
            new_name='product_type',
        ),
    ]
