# Generated by Django 4.2.5 on 2023-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0002_rename_client_id_product_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
