# Generated by Django 4.2.5 on 2023-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0003_client_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='virtual_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
