# Generated by Django 4.1.3 on 2023-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0004_client_virtual_balance_alter_client_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_buyer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
