# Generated by Django 4.1.3 on 2023-09-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0005_alter_product_product_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='client_id',
            new_name='client_username',
        ),
    ]
