# Generated by Django 4.1.3 on 2023-09-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeilaoApp', '0006_rename_client_id_product_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_password',
        ),
    ]
